### ISSUE TITLE
Error generating json from cli

### ISSUE THREAD

**Issue by ccarrero301** [scale-tone/az-func-as-a-graph#8]
I am getting this error no matter how I try to run the command:

![image](https://user-images.githubusercontent.com/22915799/133912608-b0e8a222-d1d3-433a-bcd3-b2a768d6acd0.png)

Does not work with either single quotes or double quotes, or even if a remove the quotes.

I cloned the project and ran npm install.

Node Version: 10.16.0.

Thanks.

**Comment by scale-tone** [comment]
Hi @ccarrero301 , I suspect your Node version is too old (to my best knowledge, it is already out of support) and includes an outtdated `fs` module, with no support for `fs.promises`.
Can you please try with recent Node, e.g. v14.17 ?

**Comment by ccarrero301** [comment]
@scale-tone Thanks! That was it. Thank you for the quick help!
